version: "3"
services:

  master:
    build:
      context: .
      dockerfile: ./master_Dockerfile
    working_dir: /home/tak/ANSIBLE/ansible_docker
    volumes:
      - /home/tak/ANSIBLE/ansible_docker/playbook_data
      - /home/tak/ANSIBLE/ansible_docker/config_data
    command: tail -f /dev/null

  serveur_web:
    build:
      context: . 
      dockerfile: ./serveur_Dockerfile
    command: 
      - /bin/bash
      - -c
      - |
        service ssh start
        tail -f /dev/null

  serveur_db:
    build:
      context: .
      dockerfile: ./serveur_Dockerfile
  
  serveur_lb:
    build:
      context: .
      dockerfile: ./serveur_Dockerfile
    ports:
      - 8080:80
